import 'dart:convert';
import 'package:shared_preferences/shared_preferences.dart';

/// Health & lifestyle information the nutritionist uses to compute personalized
/// daily calorie and water goals. Stored locally (SharedPreferences) so it
/// survives restarts without needing a DB migration.
class HealthProfile {
  // Body basics
  final double weightKg;
  final double heightCm;
  final int age;
  final String gender; // Male / Female / Other

  // Activity level
  final String activityLevel; // Sedentary / Light / Moderate / Active / Very Active

  // Primary goal
  final String goal; // Lose Weight / Maintain / Gain Weight

  // Health conditions (multi-select)
  final List<String> conditions; // e.g. Diabetes, Hypertension, ...

  // Financial status — affects how affordable the suggested foods are
  final String financialStatus; // Low / Medium / High

  // Optional notes
  final String notes;

  const HealthProfile({
    required this.weightKg,
    required this.heightCm,
    required this.age,
    required this.gender,
    required this.activityLevel,
    required this.goal,
    required this.conditions,
    required this.financialStatus,
    this.notes = '',
  });

  Map<String, dynamic> toJson() => {
        'weightKg': weightKg,
        'heightCm': heightCm,
        'age': age,
        'gender': gender,
        'activityLevel': activityLevel,
        'goal': goal,
        'conditions': conditions,
        'financialStatus': financialStatus,
        'notes': notes,
      };

  factory HealthProfile.fromJson(Map<String, dynamic> j) => HealthProfile(
        weightKg: (j['weightKg'] as num?)?.toDouble() ?? 70,
        heightCm: (j['heightCm'] as num?)?.toDouble() ?? 170,
        age: (j['age'] as num?)?.toInt() ?? 25,
        gender: (j['gender'] as String?) ?? 'Not specified',
        activityLevel: (j['activityLevel'] as String?) ?? 'Moderate',
        goal: (j['goal'] as String?) ?? 'Maintain',
        conditions:
            ((j['conditions'] as List?)?.map((e) => e.toString()).toList()) ??
                const [],
        financialStatus: (j['financialStatus'] as String?) ?? 'Medium',
        notes: (j['notes'] as String?) ?? '',
      );

  static const _prefsKey = 'health_profile_json';

  Future<void> save() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_prefsKey, jsonEncode(toJson()));
  }

  static Future<HealthProfile?> load() async {
    final prefs = await SharedPreferences.getInstance();
    final raw = prefs.getString(_prefsKey);
    if (raw == null || raw.isEmpty) return null;
    try {
      return HealthProfile.fromJson(jsonDecode(raw) as Map<String, dynamic>);
    } catch (_) {
      return null;
    }
  }
}

/// The nutritionist's recommendation output.
class NutritionPlan {
  final int calorieGoal; // kcal/day
  final int waterGoalMl; // ml/day
  final String explanation; // professional rationale (markdown-ish plain text)
  final List<String> tips; // short actionable tips
  final bool fromAI; // true if generated by Gemini, false if computed offline

  const NutritionPlan({
    required this.calorieGoal,
    required this.waterGoalMl,
    required this.explanation,
    required this.tips,
    required this.fromAI,
  });
}
